/**
 * Emit the golden fixtures the Foundry suite reads.
 *
 * Phase 0's completion gate is that one fixture hashes identically in the API,
 * the trial runner, the verifier and the contract tests. TypeScript computes the
 * expected values here and Solidity recomputes them from the same inputs, so a
 * divergence between the two implementations fails the build instead of
 * producing receipts nobody can reproduce.
 *
 * Run with `pnpm --filter @mandate/domain emit:fixtures`.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { canonicalHash, canonicalize } from "../src/canonical.js";
import { deriveMandateId, receiptIdOf } from "../src/ids.js";
import {
  GOLDEN_GRANTED_AUTHORITY,
  GOLDEN_TESTED_AUTHORITY,
  GOLDEN_TRIAL_RECEIPT,
  GOLDEN_TRIAL_SPEC,
} from "../src/fixtures.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const outputDir = join(repoRoot, "contracts", "fixtures");

const receipt = GOLDEN_TRIAL_RECEIPT;
const receiptId = receiptIdOf(receipt);

const grantedAuthorityHash = canonicalHash(GOLDEN_GRANTED_AUTHORITY as never);
const testedAuthorityHash = canonicalHash(GOLDEN_TESTED_AUTHORITY as never);

const mandateId = deriveMandateId({
  chainId: receipt.chainId,
  wallet: "0x4444444444444444444444444444444444444444",
  trialReceiptId: receiptId,
  grantedAuthorityHash,
  sequence: 0,
});

/**
 * Field order is meaningful: `vm.parseJson` decodes a JSON object into a
 * Solidity struct by sorting keys alphabetically, so the struct in the test must
 * be declared to match. Emitting the receipt as an explicit object rather than
 * spreading the fixture keeps that contract visible.
 */
const fixture = {
  note: "Generated by packages/domain/scripts/emit-golden-fixtures.ts. Do not edit by hand.",
  canonicalEncoding: "MCJ/1",
  receipt: {
    identityRegistry: receipt.identityRegistry,
    agentId: receipt.agentId,
    agentVersionHash: receipt.agentVersionHash,
    trialSpecHash: receipt.trialSpecHash,
    testedAuthorityHash: receipt.testedAuthorityHash,
    scenarioHash: receipt.scenarioHash,
    evaluatorHash: receipt.evaluatorHash,
    referenceModelHash: receipt.referenceModelHash,
    evidenceHash: receipt.evidenceHash,
    snapshotBlock: receipt.snapshotBlock,
    createdAt: String(receipt.createdAt),
    freshUntil: String(receipt.freshUntil),
    passed: receipt.result === "PASS",
  },
  chainId: receipt.chainId,
  publisher: receipt.publisher,
  evidenceURI: receipt.evidenceURI,
  expectedReceiptId: receiptId,

  mandate: {
    wallet: "0x4444444444444444444444444444444444444444",
    trialReceiptId: receiptId,
    grantedAuthorityHash,
    sequence: 0,
  },
  expectedMandateId: mandateId,

  documentHashes: {
    testedAuthority: testedAuthorityHash,
    grantedAuthority: grantedAuthorityHash,
    trialSpec: canonicalHash(GOLDEN_TRIAL_SPEC as never),
    trialReceipt: canonicalHash(GOLDEN_TRIAL_RECEIPT as never),
  },

  /**
   * The exact canonical bytes behind `documentHashes.testedAuthority`.
   * Included so a verifier in any language can check its own encoder against a
   * known-good string before trusting its hashes.
   */
  canonicalTestedAuthority: canonicalize(GOLDEN_TESTED_AUTHORITY as never),
};

mkdirSync(outputDir, { recursive: true });
const outputPath = join(outputDir, "golden-ids.json");
writeFileSync(outputPath, `${JSON.stringify(fixture, null, 2)}\n`, "utf8");

process.stdout.write(`wrote ${outputPath}\n`);
process.stdout.write(`  receiptId  ${receiptId}\n`);
process.stdout.write(`  mandateId  ${mandateId}\n`);
