/**
 * Freeze a live Venus account into a regression fixture.
 *
 * Captures a real account at a real block with full provenance, so
 * VENUS-ACCOUNTING-001 is asserted against chain state that actually occurred
 * rather than against numbers someone typed.
 *
 *   pnpm --filter @mandate/venus-bsc capture:fixture
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createPublicClient, http } from "viem";
import type { Address } from "viem";
import { VENUS_BSC_TESTNET } from "../src/addresses.js";
import { observeAccount } from "../src/reads.js";
import { hasDebtOutsideEnteredMarkets } from "../src/observation.js";

const RPC_URL = process.env.BSC_TESTNET_RPC_URL ?? "https://bsc-testnet-rpc.publicnode.com";

/**
 * The account behind VENUS-ACCOUNTING-001.
 *
 * It carries VAI debt and no vToken borrow, which is precisely the shape that
 * makes an entered-markets reading report "no debt" for a position that is
 * genuinely leveraged.
 */
const ACCOUNT: Address = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266";

const client = createPublicClient({ transport: http(RPC_URL) });
const blockNumber = await client.getBlockNumber();

const observation = await observeAccount(client, VENUS_BSC_TESTNET, ACCOUNT, { blockNumber });

const fixture = {
  note: "Generated by packages/venus-bsc/scripts/capture-fixture.ts. Frozen regression evidence; do not edit by hand.",
  invariant: "VENUS-ACCOUNTING-001",
  capturedAt: new Date().toISOString(),
  rpcUrl: RPC_URL,
  provenance: {
    chainId: VENUS_BSC_TESTNET.chainId,
    account: ACCOUNT,
    blockNumber: observation.blockNumber,
    blockHash: observation.blockHash,
    comptroller: VENUS_BSC_TESTNET.comptroller,
    vaiController: VENUS_BSC_TESTNET.vaiController,
  },
  observation,
  /** What the incomplete reading would have concluded, kept for the assertion. */
  brokenView: {
    method: "enumerate getAssetsIn only, treat it as the complete debt universe",
    enteredMarkets: observation.enteredMarkets,
    debtFoundByBrokenView: observation.markets
      .filter((market) => market.entered && BigInt(market.borrowBalance) > 0n)
      .map((market) => ({ vToken: market.vToken, borrowBalance: market.borrowBalance })),
    vaiDebtMissed: observation.vai.repayAmount,
    principalUnderstatement: (
      BigInt(observation.vai.repayAmount) - BigInt(observation.vai.mintedPrincipal)
    ).toString(10),
  },
  hasDebtOutsideEnteredMarkets: hasDebtOutsideEnteredMarkets(observation),
};

const here = dirname(fileURLToPath(import.meta.url));
const outputDir = join(here, "..", "fixtures");
mkdirSync(outputDir, { recursive: true });
const path = join(outputDir, "venus-accounting-001.json");
writeFileSync(path, `${JSON.stringify(fixture, null, 2)}\n`, "utf8");

process.stdout.write(
  [
    `wrote ${path}`,
    `  block                    ${observation.blockNumber}`,
    `  markets in universe      ${observation.markets.length}`,
    `  markets entered          ${observation.enteredMarkets.length}`,
    `  VAI principal            ${observation.vai.mintedPrincipal}`,
    `  VAI actually owed        ${observation.vai.repayAmount}`,
    `  liquidity / shortfall    ${observation.accountLiquidity.liquidity} / ${observation.accountLiquidity.shortfall}`,
    `  debt outside getAssetsIn ${fixture.hasDebtOutsideEnteredMarkets}`,
    "",
  ].join("\n"),
);
